### ISSUE TITLE
Null Validation - Uncaught TypeError: Cannot read property 'match' of undefined.

### ISSUE THREAD

**Issue by dolcalmi** [ember-cli/ember-resolver#101] opened 2015-07-14 21:37 UTC
I am getting the next error: Uncaught TypeError: Cannot read property 'match' of undefined.

The error comes from "podBasedComponentsInSubdir" function ->  line 202 -> validation (parsedName.fullNameWithoutType.match(/^components/).

WIth some debug I found that the problem is when parsedName.fullName is equal to "helper:@content-helper"

Not sure if is a bug of ember resolver (lack of null validation) or ember itself. 

update

I could reproduce it in an isolated environment an seems to happen when a helper is called without parameters.

{{some-helper ''}} -> ok
{{some-helper}} -> error

**Comment by mitchlloyd** [comment] 2015-07-21 22:20
I'm tracking a similar bug right now. When using angle bracket components, I get the error. Going through the code I'm not sure if the bug is in ember-resolver or if the input coming from Ember is invalid.

Here is my debugging session right when fullNameWithoutType is set to undefined. Hoping that someone in the know could determine if the input is invalid (`helper:@<new-name>`), or if there is an error in the parsing. 

This code path happens when Ember is checking to see if there is a helper named <new-name> (there is not).

<img width="970" alt="screen shot 2015-07-21 at 6 07 35 pm" src="https://cloud.githubusercontent.com/assets/15169/8813837/7013f938-2fd4-11e5-8d8a-eb832f266a4e.png">

**Comment by stefanpenner** [comment] 2015-07-21 22:22
can a reproduction repo be provided? will be easier to diagnose

**Comment by mitchlloyd** [comment] 2015-07-21 22:30
I've determined that `helper:@<new-name>` is not valid input, so this is likely a bug in Ember. I'll let you know when I have a simple reproduction.

**Comment by mitchlloyd** [comment] 2015-07-22 00:45
Finally figured out how to reliably reproduce: put a components as the top level DOM node in a template using Ember CLI.

Here is an example working in JS Bin:
http://emberjs.jsbin.com/xoyetunigi/edit?html,js,output

**Comment by knownasilya** [comment] 2015-07-24 18:27
Just ran into this as well. Is there a related issue in the ember repo?

**Comment by knownasilya** [comment] 2015-07-24 18:30
What's the best way to track down the offending element? I'm not using any custom elements..

**Comment by knownasilya** [comment] 2015-07-24 19:00
So for me it was using the `{{title}}` helper from https://github.com/paddle8/ember-document-title and an attribute `{{title}}` that were colliding.

**Comment by rwjblue** [comment] 2015-08-05 17:08
Cross posting from https://github.com/emberjs/ember.js/issues/11987: 

The issue is ultimately with the ember-cli resolver (and there is a tracking issue over in https://github.com/ember-cli/ember-resolver/issues/101).  

Basically, what is happening is that if you use a dashless helper without ordered or hash arguments, we end up trying to look for an `helper:@content-helper` ([deep inside HTMLBars](https://github.com/tildeio/htmlbars/blob/dc4bbf197853ab6f868163bf43c654427f95d2ab/packages/htmlbars-runtime/lib/hooks.js#L755)), and the ember-cli resolver has been updated to use `@` as a namespace separator (so it expects `helper:addon-name@helper-name` format) so it does not have a `fullnameWithoutType` (which it is using to do a regexp match against).

We need to fix the [parseName](https://github.com/ember-cli/ember-resolver/blob/master/packages/ember-resolver/lib/core.js#L52-L85) function to deal with `helper:@content-helper` properly.

**Comment by knownasilya** [comment] 2015-08-05 17:35
@rwjblue this is #101.. did you mean to reference some other issue?

**Comment by tim-evans** [comment] 2015-08-05 18:19
There's a reduced test case for this with http://ember-twiddle.com/66a300bd7e8ecee24379. (Thanks @rwjblue) I would really like not to have to change the API again of ember-document-title to deal with this particular case. I'd like to help with this if possible, since this directly affects my addon.

**Comment by rwjblue** [comment] 2015-08-05 18:31
> I would really like not to have to change the API again of ember-document-title to deal with this particular case

Using a dashless helper without params or hash params should totallly work and should not require changing your addon's API. 

> I'd like to help with this if possible, since this directly affects my addon.

Awesome, thank you! We need to add a test case and handle `helper:@content-name` in the `parseName` function.  If you have the time, could you rebase https://github.com/ember-cli/ember-resolver/pull/92 and submit as another PR adding a test for the scenario I mentioned above (beware the build system for this repo is pretty outdated)?

**Comment by rwjblue** [comment] 2015-08-05 18:54
@tim-evans - Thanks for updating #92, that change is in so we can work on the fix for `helper:@content-helper` case next...

**Comment by tim-evans** [comment] 2015-08-05 18:55
Super!

**Comment by kategengler** [comment] 2023-06-15 20:49
Closing due to age. Fairly sure this isn't an issue anymore but if it is, a modern reproduction would be appreciated.

**Closed by kategengler** 2023-06-15 20:49 UTC
